import 'package:flutter/material.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedPin13Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedIconmonstrlogout92401Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedPin16Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedRectangle50Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedIconmonstrspeechbubble724011Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedPerfilWidget6.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedTela_artistaWidget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedTest4Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedTest2Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedTelaInicialWidget10.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedSairWidget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedOlMechamoErickSebastioesouumartistaannimonoramodaspintu9.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedRectangle16Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedFoto_perfil1Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedTest3Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedTest1Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedChatWidget10.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedRectangle18Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedIconmonstrarrow632401Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedRectangle15Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedIconmonstruser1924011Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedIconmonstrarrow6324011Widget5.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedErickSebastioWidget13.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedVoltarWidget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedRectangle14Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedMapa1Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedPauloSantiagoWidget10.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedIconmonstrhome624011Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedRectangle19Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedPin17Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedRectangle20Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget1/generated/GeneratedRectangle17Widget2.dart';

/* Frame Tela de Home_Clicar_No_Artista
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTeladeHome_Clicar_No_ArtistaWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 948.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                          begin: Alignment(0.0, -1.0),
                          end: Alignment(0.0, 0.9999999999999998),
                          stops: [0.125, 0.921875],
                          colors: [
                            Color.fromARGB(255, 155, 7, 179),
                            Color.fromARGB(255, 69, 8, 95)
                          ],
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(51, 0, 0, 0),
                              ),
                            ),
                            Positioned(
                              left: -258.0,
                              top: 59.0,
                              right: null,
                              bottom: null,
                              width: 800.0,
                              height: 807.0,
                              child: GeneratedMapa1Widget2(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 585.0,
                              right: null,
                              bottom: null,
                              width: 402.0,
                              height: 348.0,
                              child: GeneratedTela_artistaWidget1(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 800.0,
                              right: null,
                              bottom: null,
                              width: 96.0,
                              height: 77.0,
                              child: GeneratedRectangle17Widget2(),
                            ),
                            Positioned(
                              left: 166.0,
                              top: 800.0,
                              right: null,
                              bottom: null,
                              width: 96.0,
                              height: 77.0,
                              child: GeneratedRectangle18Widget1(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 800.0,
                              right: null,
                              bottom: null,
                              width: 96.0,
                              height: 77.0,
                              child: GeneratedRectangle20Widget1(),
                            ),
                            Positioned(
                              left: 272.0,
                              top: 800.0,
                              right: null,
                              bottom: null,
                              width: 96.0,
                              height: 77.0,
                              child: GeneratedRectangle19Widget1(),
                            ),
                            Positioned(
                              left: -9.0,
                              top: 850.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 98.0,
                              child: GeneratedRectangle14Widget3(),
                            ),
                            Positioned(
                              left: -44.0,
                              top: 2.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 65.0,
                              child: GeneratedRectangle15Widget3(),
                            ),
                            Positioned(
                              left: 340.0,
                              top: 379.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedIconmonstrarrow6324011Widget5(),
                            ),
                            Positioned(
                              left: 307.0,
                              top: 874.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedIconmonstruser1924011Widget2(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 7.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 47.0,
                              child: GeneratedFoto_perfil1Widget2(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstrhome624011Widget2(),
                            ),
                            Positioned(
                              left: 199.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child:
                                  GeneratedIconmonstrspeechbubble724011Widget2(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 53.0,
                              height: 14.0,
                              child: GeneratedTelaInicialWidget10(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 17.0,
                              child: GeneratedChatWidget10(),
                            ),
                            Positioned(
                              left: 308.0,
                              top: 910.0,
                              right: null,
                              bottom: null,
                              width: 31.0,
                              height: 17.0,
                              child: GeneratedPerfilWidget6(),
                            ),
                            Positioned(
                              left: 71.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 111.0,
                              height: 20.0,
                              child: GeneratedPauloSantiagoWidget10(),
                            ),
                            Positioned(
                              left: 102.0,
                              top: 466.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedPin13Widget1(),
                            ),
                            Positioned(
                              left: 107.0,
                              top: 467.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedTest1Widget1(),
                            ),
                            Positioned(
                              left: 178.0,
                              top: 502.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedPin16Widget2(),
                            ),
                            Positioned(
                              left: 188.0,
                              top: 503.0,
                              right: null,
                              bottom: null,
                              width: 40.0,
                              height: 41.0,
                              child: GeneratedTest2Widget2(),
                            ),
                            Positioned(
                              left: 277.0,
                              top: 472.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedPin17Widget2(),
                            ),
                            Positioned(
                              left: 282.0,
                              top: 473.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedTest3Widget2(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 655.0,
                              right: null,
                              bottom: null,
                              width: 95.0,
                              height: 95.0,
                              child: GeneratedTest4Widget2(),
                            ),
                            Positioned(
                              left: 161.0,
                              top: 598.0,
                              right: null,
                              bottom: null,
                              width: 102.0,
                              height: 8.0,
                              child: GeneratedRectangle16Widget2(),
                            ),
                            Positioned(
                              left: 148.0,
                              top: 664.0,
                              right: null,
                              bottom: null,
                              width: 130.0,
                              height: 23.0,
                              child: GeneratedErickSebastioWidget13(),
                            ),
                            Positioned(
                              left: 148.0,
                              top: 695.0,
                              right: null,
                              bottom: null,
                              width: 395.0,
                              height: 85.0,
                              child:
                                  GeneratedOlMechamoErickSebastioesouumartistaannimonoramodaspintu9(),
                            ),
                            Positioned(
                              left: 237.0,
                              top: -17.0,
                              right: null,
                              bottom: null,
                              width: 191.0,
                              height: 943.0,
                              child: GeneratedRectangle50Widget2(),
                            ),
                            Positioned(
                              left: 311.0,
                              top: 35.0,
                              right: null,
                              bottom: null,
                              width: 63.0,
                              height: 29.0,
                              child: GeneratedVoltarWidget2(),
                            ),
                            Positioned(
                              left: 292.0,
                              top: 114.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 26.0,
                              child: GeneratedSairWidget2(),
                            ),
                            Positioned(
                              left: 254.0,
                              top: 111.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 29.0,
                              child: GeneratedIconmonstrlogout92401Widget2(),
                            ),
                            Positioned(
                              left: 284.0,
                              top: 39.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 17.22488021850586,
                              child: GeneratedIconmonstrarrow632401Widget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
