import 'package:flutter/material.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedRectangle57Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedIconmonstrhome624015Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedChatWidget21.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedErikaCristinaWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedFoiumprazerfazernegciocomvocWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedRectangle58Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedIconmonstruser1924014Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedRobertLorenzoWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedRectangle59Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedRectangle61Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedIconmonstrspeechbubble724015Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedAlbertoSanchezWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedEllipse4Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/Generated11Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedCertocertoWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedRectangle60Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedTest10Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedTest7Widget5.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedInfelizmentenoatendonessaregioWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/Generated1600Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/Generated1600Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedIconmonstrarrow6324013Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedFoto_perfil2Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedErickSebastioWidget21.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedTelaInicialWidget21.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedTest8Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedDisponhaSequiseroutraartefalecomigoWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedTest9Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedRectangle18Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedPauloSantiagoWidget19.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/GeneratedPerfilWidget14.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/Generated1600Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget/generated/Generated1600Widget1.dart';

/* Frame Tela_Cliente_Chats
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTela_Cliente_ChatsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 948.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 249, 234, 234),
                              ),
                            ),
                            Positioned(
                              left: -44.0,
                              top: 2.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 65.0,
                              child: GeneratedRectangle18Widget2(),
                            ),
                            Positioned(
                              left: 6.0,
                              top: 89.0,
                              right: null,
                              bottom: null,
                              width: 415.0,
                              height: 98.0,
                              child: GeneratedRectangle58Widget(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 7.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 47.0,
                              child: GeneratedFoto_perfil2Widget4(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 19.0,
                              right: null,
                              bottom: null,
                              width: 147.0,
                              height: 26.0,
                              child: GeneratedPauloSantiagoWidget19(),
                            ),
                            Positioned(
                              left: 383.0,
                              top: 20.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedIconmonstrarrow6324013Widget3(),
                            ),
                            Positioned(
                              left: -9.0,
                              top: 850.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 98.0,
                              child: GeneratedRectangle57Widget(),
                            ),
                            Positioned(
                              left: 322.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstruser1924014Widget(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 53.0,
                              height: 14.0,
                              child: GeneratedTelaInicialWidget21(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 17.0,
                              child: GeneratedChatWidget21(),
                            ),
                            Positioned(
                              left: 202.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child:
                                  GeneratedIconmonstrspeechbubble724015Widget(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstrhome624015Widget(),
                            ),
                            Positioned(
                              left: 327.0,
                              top: 902.0,
                              right: null,
                              bottom: null,
                              width: 31.0,
                              height: 17.0,
                              child: GeneratedPerfilWidget14(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 104.0,
                              right: null,
                              bottom: null,
                              width: 66.27586364746094,
                              height: 62.0,
                              child: GeneratedTest7Widget5(),
                            ),
                            Positioned(
                              left: 117.0,
                              top: 105.0,
                              right: null,
                              bottom: null,
                              width: 125.0,
                              height: 20.0,
                              child: GeneratedErickSebastioWidget21(),
                            ),
                            Positioned(
                              left: 119.0,
                              top: 127.0,
                              right: null,
                              bottom: null,
                              width: 266.0,
                              height: 35.0,
                              child: GeneratedCertocertoWidget(),
                            ),
                            Positioned(
                              left: 365.0,
                              top: 158.0,
                              right: null,
                              bottom: null,
                              width: 19.0,
                              height: 18.0,
                              child: GeneratedEllipse4Widget(),
                            ),
                            Positioned(
                              left: 369.0,
                              top: 159.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 22.0,
                              child: Generated11Widget(),
                            ),
                            Positioned(
                              left: 6.0,
                              top: 203.0,
                              right: null,
                              bottom: null,
                              width: 415.0,
                              height: 98.0,
                              child: GeneratedRectangle59Widget(),
                            ),
                            Positioned(
                              left: 45.0,
                              top: 220.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 62.0,
                              child: GeneratedTest8Widget1(),
                            ),
                            Positioned(
                              left: 117.0,
                              top: 216.0,
                              right: null,
                              bottom: null,
                              width: 105.0,
                              height: 21.0,
                              child: GeneratedErikaCristinaWidget(),
                            ),
                            Positioned(
                              left: 118.0,
                              top: 248.0,
                              right: null,
                              bottom: null,
                              width: 244.0,
                              height: 18.0,
                              child:
                                  GeneratedFoiumprazerfazernegciocomvocWidget(),
                            ),
                            Positioned(
                              left: 6.0,
                              top: 316.0,
                              right: null,
                              bottom: null,
                              width: 415.0,
                              height: 98.0,
                              child: GeneratedRectangle60Widget(),
                            ),
                            Positioned(
                              left: 47.0,
                              top: 331.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 60.0,
                              child: GeneratedTest9Widget(),
                            ),
                            Positioned(
                              left: 120.0,
                              top: 325.0,
                              right: null,
                              bottom: null,
                              width: 125.0,
                              height: 21.0,
                              child: GeneratedRobertLorenzoWidget(),
                            ),
                            Positioned(
                              left: 117.0,
                              top: 354.0,
                              right: null,
                              bottom: null,
                              width: 280.0,
                              height: 18.0,
                              child:
                                  GeneratedDisponhaSequiseroutraartefalecomigoWidget(),
                            ),
                            Positioned(
                              left: 6.0,
                              top: 430.0,
                              right: null,
                              bottom: null,
                              width: 415.0,
                              height: 98.0,
                              child: GeneratedRectangle61Widget(),
                            ),
                            Positioned(
                              left: 47.0,
                              top: 445.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedTest10Widget(),
                            ),
                            Positioned(
                              left: 118.0,
                              top: 440.0,
                              right: null,
                              bottom: null,
                              width: 131.0,
                              height: 21.0,
                              child: GeneratedAlbertoSanchezWidget(),
                            ),
                            Positioned(
                              left: 120.0,
                              top: 470.0,
                              right: null,
                              bottom: null,
                              width: 241.0,
                              height: 18.0,
                              child:
                                  GeneratedInfelizmentenoatendonessaregioWidget(),
                            ),
                            Positioned(
                              left: 345.0,
                              top: 105.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 23.0,
                              child: Generated1600Widget(),
                            ),
                            Positioned(
                              left: 349.0,
                              top: 217.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 23.0,
                              child: Generated1600Widget1(),
                            ),
                            Positioned(
                              left: 315.0,
                              top: 323.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 23.0,
                              child: Generated1600Widget2(),
                            ),
                            Positioned(
                              left: 317.0,
                              top: 439.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 23.0,
                              child: Generated1600Widget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
