import 'package:flutter/material.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedTest6Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedIconmonstrspeechbubble724013Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedRectangle44Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedRectangle37Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedTelaInicialWidget11.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedRectangle39Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedPauloSantiagoWidget12.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedRectangle50Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedFalarcomartistaWidget8.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedRectangle21Widget8.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedOlMechamopauloecomproserviosartisticosWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedErickSebastioWidget14.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedRectangle33Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedIconmonstrspeechbubble724012Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedTelaInicialWidget12.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedPauloSantiagoWidget11.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedRectangle34Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedFoto_perfil3Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedRectangle36Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedChatWidget12.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedIconmonstrhome624013Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedIconmonstruser1924012Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedRectangle43Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedRectangle35Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedRectangle42Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedOlMechamoErickSebastioesouumartistaannimonoramodaspintu10.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedRectangle38Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedIconmonstrspeechbubble62402Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedPerfilWidget7.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedChatWidget11.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedRectangle45Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedIconmonstrarrow6324012Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedRectangle41Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedTest7Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedIconmonstrhome624012Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_usuariowidget/generated/GeneratedRectangle40Widget4.dart';

/* Frame Tela_usuario
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTela_usuarioWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 948.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 249, 234, 234),
                              ),
                            ),
                            Positioned(
                              left: 156.0,
                              top: 122.0,
                              right: null,
                              bottom: null,
                              width: 147.0,
                              height: 26.0,
                              child: GeneratedPauloSantiagoWidget11(),
                            ),
                            Positioned(
                              left: 156.0,
                              top: 152.0,
                              right: null,
                              bottom: null,
                              width: 213.0,
                              height: 85.0,
                              child:
                                  GeneratedOlMechamopauloecomproserviosartisticosWidget(),
                            ),
                            Positioned(
                              left: -9.0,
                              top: 850.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 98.0,
                              child: GeneratedRectangle21Widget8(),
                            ),
                            Positioned(
                              left: 322.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstruser1924012Widget4(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstrhome624012Widget4(),
                            ),
                            Positioned(
                              left: 202.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child:
                                  GeneratedIconmonstrspeechbubble724012Widget4(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 53.0,
                              height: 14.0,
                              child: GeneratedTelaInicialWidget11(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 17.0,
                              child: GeneratedChatWidget11(),
                            ),
                            Positioned(
                              left: 327.0,
                              top: 902.0,
                              right: null,
                              bottom: null,
                              width: 31.0,
                              height: 17.0,
                              child: GeneratedPerfilWidget7(),
                            ),
                            Positioned(
                              left: 490.0,
                              top: 433.0,
                              right: null,
                              bottom: null,
                              width: 82.0,
                              height: 82.0,
                              child: GeneratedTest6Widget4(),
                            ),
                            Positioned(
                              left: 583.0,
                              top: 439.0,
                              right: null,
                              bottom: null,
                              width: 122.0,
                              height: 21.0,
                              child: GeneratedErickSebastioWidget14(),
                            ),
                            Positioned(
                              left: 583.0,
                              top: 462.0,
                              right: null,
                              bottom: null,
                              width: 213.0,
                              height: 85.0,
                              child:
                                  GeneratedOlMechamoErickSebastioesouumartistaannimonoramodaspintu10(),
                            ),
                            Positioned(
                              left: 468.0,
                              top: 358.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 65.0,
                              child: GeneratedRectangle33Widget4(),
                            ),
                            Positioned(
                              left: 490.0,
                              top: 363.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 47.0,
                              child: GeneratedFoto_perfil3Widget4(),
                            ),
                            Positioned(
                              left: 547.0,
                              top: 378.0,
                              right: null,
                              bottom: null,
                              width: 111.0,
                              height: 20.0,
                              child: GeneratedPauloSantiagoWidget12(),
                            ),
                            Positioned(
                              left: 491.0,
                              top: 563.0,
                              right: null,
                              bottom: null,
                              width: 94.0,
                              height: 94.0,
                              child: GeneratedRectangle34Widget4(),
                            ),
                            Positioned(
                              left: 491.0,
                              top: 563.0,
                              right: null,
                              bottom: null,
                              width: 94.0,
                              height: 94.0,
                              child: GeneratedRectangle35Widget4(),
                            ),
                            Positioned(
                              left: 597.0,
                              top: 563.0,
                              right: null,
                              bottom: null,
                              width: 94.0,
                              height: 94.0,
                              child: GeneratedRectangle36Widget4(),
                            ),
                            Positioned(
                              left: 703.0,
                              top: 563.0,
                              right: null,
                              bottom: null,
                              width: 94.0,
                              height: 94.0,
                              child: GeneratedRectangle37Widget4(),
                            ),
                            Positioned(
                              left: 491.0,
                              top: 672.0,
                              right: null,
                              bottom: null,
                              width: 94.0,
                              height: 94.0,
                              child: GeneratedRectangle38Widget4(),
                            ),
                            Positioned(
                              left: 597.0,
                              top: 672.0,
                              right: null,
                              bottom: null,
                              width: 94.0,
                              height: 94.0,
                              child: GeneratedRectangle39Widget4(),
                            ),
                            Positioned(
                              left: 703.0,
                              top: 672.0,
                              right: null,
                              bottom: null,
                              width: 94.0,
                              height: 94.0,
                              child: GeneratedRectangle40Widget4(),
                            ),
                            Positioned(
                              left: 491.0,
                              top: 781.0,
                              right: null,
                              bottom: null,
                              width: 94.0,
                              height: 94.0,
                              child: GeneratedRectangle41Widget4(),
                            ),
                            Positioned(
                              left: 597.0,
                              top: 781.0,
                              right: null,
                              bottom: null,
                              width: 94.0,
                              height: 94.0,
                              child: GeneratedRectangle42Widget4(),
                            ),
                            Positioned(
                              left: 703.0,
                              top: 781.0,
                              right: null,
                              bottom: null,
                              width: 94.0,
                              height: 94.0,
                              child: GeneratedRectangle43Widget4(),
                            ),
                            Positioned(
                              left: 433.0,
                              top: 869.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 65.0,
                              child: GeneratedRectangle44Widget4(),
                            ),
                            Positioned(
                              left: 524.0,
                              top: 874.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedIconmonstrhome624013Widget4(),
                            ),
                            Positioned(
                              left: 631.0,
                              top: 874.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child:
                                  GeneratedIconmonstrspeechbubble724013Widget4(),
                            ),
                            Positioned(
                              left: 514.0,
                              top: 910.0,
                              right: null,
                              bottom: null,
                              width: 53.0,
                              height: 14.0,
                              child: GeneratedTelaInicialWidget12(),
                            ),
                            Positioned(
                              left: 634.0,
                              top: 910.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 17.0,
                              child: GeneratedChatWidget12(),
                            ),
                            Positioned(
                              left: 641.0,
                              top: 818.0,
                              right: null,
                              bottom: null,
                              width: 153.0,
                              height: 38.0,
                              child: GeneratedRectangle45Widget4(),
                            ),
                            Positioned(
                              left: 677.0,
                              top: 828.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 18.0,
                              child: GeneratedFalarcomartistaWidget8(),
                            ),
                            Positioned(
                              left: 650.0,
                              top: 824.0,
                              right: null,
                              bottom: null,
                              width: 25.0,
                              height: 25.0,
                              child:
                                  GeneratedIconmonstrspeechbubble62402Widget4(),
                            ),
                            Positioned(
                              left: 382.0,
                              top: 35.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedIconmonstrarrow6324012Widget1(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 104.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 120.0,
                              child: GeneratedTest7Widget4(),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 291.0,
                              right: null,
                              bottom: null,
                              width: 119.0,
                              height: 119.0,
                              child: GeneratedRectangle50Widget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
