import 'package:flutter/material.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget/generated/GeneratedTest3Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget/generated/GeneratedIconmonstrarrow6324012Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget/generated/GeneratedIconmonstrspeechbubble724011Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget/generated/GeneratedRectangle14Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget/generated/GeneratedMapa1Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget/generated/GeneratedTest4Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget/generated/GeneratedPerfilWidget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget/generated/GeneratedChatWidget8.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget/generated/GeneratedFoto_perfil1Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget/generated/GeneratedRectangle15Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget/generated/GeneratedPin17Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget/generated/GeneratedIconmonstrhome624011Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget/generated/GeneratedPin18Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget/generated/GeneratedIconmonstruser1924011Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget/generated/GeneratedTelaInicialWidget8.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget/generated/GeneratedTest2Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget/generated/GeneratedPauloSantiagoWidget8.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget/generated/GeneratedPin16Widget.dart';

/* Frame Tela de Home_Cliente
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTeladeHome_ClienteWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 948.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                          begin: Alignment(0.0, -1.0),
                          end: Alignment(0.0, 0.9999999999999998),
                          stops: [0.125, 0.921875],
                          colors: [
                            Color.fromARGB(255, 155, 7, 179),
                            Color.fromARGB(255, 69, 8, 95)
                          ],
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(51, 0, 0, 0),
                              ),
                            ),
                            Positioned(
                              left: -262.0,
                              top: 56.0,
                              right: null,
                              bottom: null,
                              width: 800.0,
                              height: 818.0,
                              child: GeneratedMapa1Widget(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 800.0,
                              right: null,
                              bottom: null,
                              width: 96.0,
                              height: 77.0,
                              child: GeneratedRectangle17Widget(),
                            ),
                            Positioned(
                              left: -9.0,
                              top: 850.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 98.0,
                              child: GeneratedRectangle14Widget1(),
                            ),
                            Positioned(
                              left: -44.0,
                              top: 2.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 65.0,
                              child: GeneratedRectangle15Widget1(),
                            ),
                            Positioned(
                              left: 322.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstruser1924011Widget(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 7.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 48.958335876464844,
                              child: GeneratedFoto_perfil1Widget(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstrhome624011Widget(),
                            ),
                            Positioned(
                              left: 202.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child:
                                  GeneratedIconmonstrspeechbubble724011Widget(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 53.0,
                              height: 14.0,
                              child: GeneratedTelaInicialWidget8(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 17.0,
                              child: GeneratedChatWidget8(),
                            ),
                            Positioned(
                              left: 327.0,
                              top: 902.0,
                              right: null,
                              bottom: null,
                              width: 31.0,
                              height: 17.0,
                              child: GeneratedPerfilWidget4(),
                            ),
                            Positioned(
                              left: 71.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 125.0,
                              height: 23.0,
                              child: GeneratedPauloSantiagoWidget8(),
                            ),
                            Positioned(
                              left: 178.0,
                              top: 557.0,
                              right: null,
                              bottom: null,
                              width: 71.0,
                              height: 71.0,
                              child: GeneratedPin16Widget(),
                            ),
                            Positioned(
                              left: 189.0,
                              top: 559.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 48.0,
                              child: GeneratedTest2Widget(),
                            ),
                            Positioned(
                              left: 318.0,
                              top: 430.0,
                              right: null,
                              bottom: null,
                              width: 69.0,
                              height: 71.0,
                              child: GeneratedPin17Widget(),
                            ),
                            Positioned(
                              left: 329.0,
                              top: 432.0,
                              right: null,
                              bottom: null,
                              width: 47.0,
                              height: 48.0,
                              child: GeneratedTest3Widget(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 432.0,
                              right: null,
                              bottom: null,
                              width: 71.0,
                              height: 71.0,
                              child: GeneratedPin18Widget(),
                            ),
                            Positioned(
                              left: 71.0,
                              top: 435.0,
                              right: null,
                              bottom: null,
                              width: 49.0,
                              height: 47.0,
                              child: GeneratedTest4Widget(),
                            ),
                            Positioned(
                              left: 383.0,
                              top: 20.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedIconmonstrarrow6324012Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
