import 'package:flutter/material.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget/generated/GeneratedIconmonstrhome624014Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget/generated/GeneratedFrame27Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget/generated/GeneratedRectangle51Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget/generated/GeneratedIconmonstrarrow6324014Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget/generated/GeneratedFoto_perfil6Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget/generated/GeneratedPerfilWidget18.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget/generated/GeneratedIconmonstrarrow6324015Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget/generated/GeneratedEllipse5Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget/generated/GeneratedTelaInicialWidget25.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget/generated/GeneratedIconmonstrspeechbubble724014Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget/generated/GeneratedChatWidget25.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget/generated/GeneratedLine26Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget/generated/GeneratedRectangle50Widget10.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget/generated/GeneratedErickSebastioWidget25.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget/generated/GeneratedIconmonstruser1924013Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget/generated/GeneratedDigiteumtextoWidget.dart';

/* Frame Tela_Chat_Cliente
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTela_Chat_ClienteWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 948.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -44.0,
                              top: 2.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 65.0,
                              child: GeneratedRectangle50Widget10(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 7.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 47.0,
                              child: GeneratedFoto_perfil6Widget2(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 19.0,
                              right: null,
                              bottom: null,
                              width: 152.0,
                              height: 26.0,
                              child: GeneratedErickSebastioWidget25(),
                            ),
                            Positioned(
                              left: 383.0,
                              top: 20.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedIconmonstrarrow6324014Widget(),
                            ),
                            Positioned(
                              left: 338.0,
                              top: 801.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedIconmonstrarrow6324015Widget(),
                            ),
                            Positioned(
                              left: -3.0,
                              top: 850.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 98.0,
                              child: GeneratedRectangle51Widget1(),
                            ),
                            Positioned(
                              left: 322.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstruser1924013Widget1(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstrhome624014Widget1(),
                            ),
                            Positioned(
                              left: 202.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child:
                                  GeneratedIconmonstrspeechbubble724014Widget1(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 53.0,
                              height: 14.0,
                              child: GeneratedTelaInicialWidget25(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 17.0,
                              child: GeneratedChatWidget25(),
                            ),
                            Positioned(
                              left: 327.0,
                              top: 902.0,
                              right: null,
                              bottom: null,
                              width: 31.0,
                              height: 17.0,
                              child: GeneratedPerfilWidget18(),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 779.0,
                              right: null,
                              bottom: null,
                              width: 338.0,
                              height: 56.0,
                              child: GeneratedRectangle1Widget(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 798.0,
                              right: null,
                              bottom: null,
                              width: 203.0,
                              height: 17.0,
                              child: GeneratedDigiteumtextoWidget(),
                            ),
                            Positioned(
                              left: 317.0,
                              top: 793.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 1.0,
                              child: GeneratedLine26Widget(),
                            ),
                            Positioned(
                              left: 328.0,
                              top: 791.0,
                              right: null,
                              bottom: null,
                              width: 35.0,
                              height: 35.0,
                              child: GeneratedEllipse5Widget(),
                            ),
                            Positioned(
                              left: 51.0,
                              top: 90.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 625.0,
                              child: GeneratedFrame27Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
