import 'package:flutter/material.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget/generated/GeneratedErickSebastioWidget23.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget/generated/GeneratedPauloSantiagoWidget21.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget/generated/GeneratedIconmonstrarrow6324013Widget5.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget/generated/GeneratedIconmonstrhome624015Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget/generated/GeneratedTelaInicialWidget23.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget/generated/GeneratedFoto_perfil6Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget/generated/Generated1600Widget8.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget/generated/GeneratedIconmonstrspeechbubble724015Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget/generated/GeneratedIconmonstruser1924014Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget/generated/GeneratedTest11Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget/generated/GeneratedCertocertoWidget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget/generated/GeneratedPerfilWidget16.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget/generated/GeneratedRectangle58Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget/generated/GeneratedRectangle18Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget/generated/GeneratedChatWidget23.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget/generated/GeneratedRectangle57Widget2.dart';

/* Frame Tela_Artista_Chats
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTela_Artista_ChatsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 948.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 249, 234, 234),
                              ),
                            ),
                            Positioned(
                              left: -41.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 65.0,
                              child: GeneratedRectangle18Widget4(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 7.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 47.0,
                              child: GeneratedFoto_perfil6Widget(),
                            ),
                            Positioned(
                              left: 71.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 115.0,
                              height: 20.0,
                              child: GeneratedErickSebastioWidget23(),
                            ),
                            Positioned(
                              left: 6.0,
                              top: 89.0,
                              right: null,
                              bottom: null,
                              width: 415.0,
                              height: 98.0,
                              child: GeneratedRectangle58Widget2(),
                            ),
                            Positioned(
                              left: 383.0,
                              top: 20.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedIconmonstrarrow6324013Widget5(),
                            ),
                            Positioned(
                              left: -9.0,
                              top: 850.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 98.0,
                              child: GeneratedRectangle57Widget2(),
                            ),
                            Positioned(
                              left: 322.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstruser1924014Widget2(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 53.0,
                              height: 14.0,
                              child: GeneratedTelaInicialWidget23(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 17.0,
                              child: GeneratedChatWidget23(),
                            ),
                            Positioned(
                              left: 202.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child:
                                  GeneratedIconmonstrspeechbubble724015Widget2(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstrhome624015Widget2(),
                            ),
                            Positioned(
                              left: 327.0,
                              top: 902.0,
                              right: null,
                              bottom: null,
                              width: 31.0,
                              height: 17.0,
                              child: GeneratedPerfilWidget16(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 104.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 62.0,
                              child: GeneratedTest11Widget(),
                            ),
                            Positioned(
                              left: 117.0,
                              top: 105.0,
                              right: null,
                              bottom: null,
                              width: 118.0,
                              height: 21.0,
                              child: GeneratedPauloSantiagoWidget21(),
                            ),
                            Positioned(
                              left: 196.0,
                              top: 127.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 15.0,
                              child: GeneratedCertocertoWidget1(),
                            ),
                            Positioned(
                              left: 345.0,
                              top: 105.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 23.0,
                              child: Generated1600Widget8(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
