import 'package:flutter/material.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedStar1Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedChatWidget22.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedRectangle57Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedTest9Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedIconmonstrarrow6324013Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedTest7Widget6.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedSairWidget7.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/Generated1600Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedInfelizmentenoatendonessaregioWidget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedFechadoAmanhestareiaiparaoserviWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedRectangle58Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedTelaInicialWidget22.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedRectangle61Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedRectangle18Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedRectangle59Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/Generated1600Widget6.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedFoto_perfil2Widget5.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedAlbertoSanchezWidget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedIconmonstruser1924014Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedTest10Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedPauloSantiagoWidget20.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedTest8Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedFoiumprazerfazernegciocomvocWidget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedIconmonstrlogout92401Widget7.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedErickSebastioWidget22.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/Generated1600Widget7.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedErikaCristinaWidget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedRectangle50Widget8.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedVoltarWidget7.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedIconmonstrspeechbubble724015Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedPerfilWidget15.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedIconmonstrhome624015Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedRectangle60Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/Generated1600Widget5.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedEllipse4Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedIconmonstrarrow632401Widget7.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/Generated2Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedDisponhaSequiseroutraartefalecomigoWidget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_cliente_chatswidget1/generated/GeneratedRobertLorenzoWidget1.dart';

/* Frame Tela_Cliente_Chats
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTela_Cliente_ChatsWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 948.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 249, 234, 234),
                              ),
                            ),
                            Positioned(
                              left: -44.0,
                              top: 2.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 65.0,
                              child: GeneratedRectangle18Widget3(),
                            ),
                            Positioned(
                              left: 6.0,
                              top: 89.0,
                              right: null,
                              bottom: null,
                              width: 320.0,
                              height: 90.0,
                              child: GeneratedRectangle58Widget1(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 7.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 47.0,
                              child: GeneratedFoto_perfil2Widget5(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 19.0,
                              right: null,
                              bottom: null,
                              width: 147.0,
                              height: 26.0,
                              child: GeneratedPauloSantiagoWidget20(),
                            ),
                            Positioned(
                              left: 340.0,
                              top: 378.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedIconmonstrarrow6324013Widget4(),
                            ),
                            Positioned(
                              left: -2.0,
                              top: 850.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 98.0,
                              child: GeneratedRectangle57Widget1(),
                            ),
                            Positioned(
                              left: 304.0,
                              top: 874.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedIconmonstruser1924014Widget1(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 53.0,
                              height: 14.0,
                              child: GeneratedTelaInicialWidget22(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 17.0,
                              child: GeneratedChatWidget22(),
                            ),
                            Positioned(
                              left: 202.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child:
                                  GeneratedIconmonstrspeechbubble724015Widget1(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstrhome624015Widget1(),
                            ),
                            Positioned(
                              left: 306.0,
                              top: 910.0,
                              right: null,
                              bottom: null,
                              width: 31.0,
                              height: 17.0,
                              child: GeneratedPerfilWidget15(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 104.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedTest7Widget6(),
                            ),
                            Positioned(
                              left: 117.0,
                              top: 105.0,
                              right: null,
                              bottom: null,
                              width: 122.0,
                              height: 21.0,
                              child: GeneratedErickSebastioWidget22(),
                            ),
                            Positioned(
                              left: 119.0,
                              top: 127.0,
                              right: null,
                              bottom: null,
                              width: 264.0,
                              height: 18.0,
                              child:
                                  GeneratedFechadoAmanhestareiaiparaoserviWidget(),
                            ),
                            Positioned(
                              left: 329.0,
                              top: 498.0,
                              right: null,
                              bottom: null,
                              width: 19.0,
                              height: 19.0,
                              child: GeneratedEllipse4Widget1(),
                            ),
                            Positioned(
                              left: 334.0,
                              top: 499.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 23.0,
                              child: Generated2Widget(),
                            ),
                            Positioned(
                              left: 6.0,
                              top: 203.0,
                              right: null,
                              bottom: null,
                              width: 415.0,
                              height: 98.0,
                              child: GeneratedRectangle59Widget1(),
                            ),
                            Positioned(
                              left: 45.0,
                              top: 220.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedTest8Widget2(),
                            ),
                            Positioned(
                              left: 117.0,
                              top: 216.0,
                              right: null,
                              bottom: null,
                              width: 105.0,
                              height: 21.0,
                              child: GeneratedErikaCristinaWidget1(),
                            ),
                            Positioned(
                              left: 118.0,
                              top: 248.0,
                              right: null,
                              bottom: null,
                              width: 244.0,
                              height: 18.0,
                              child:
                                  GeneratedFoiumprazerfazernegciocomvocWidget1(),
                            ),
                            Positioned(
                              left: 6.0,
                              top: 316.0,
                              right: null,
                              bottom: null,
                              width: 415.0,
                              height: 98.0,
                              child: GeneratedRectangle60Widget1(),
                            ),
                            Positioned(
                              left: 47.0,
                              top: 331.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedTest9Widget1(),
                            ),
                            Positioned(
                              left: 120.0,
                              top: 325.0,
                              right: null,
                              bottom: null,
                              width: 121.0,
                              height: 21.0,
                              child: GeneratedRobertLorenzoWidget1(),
                            ),
                            Positioned(
                              left: 117.0,
                              top: 354.0,
                              right: null,
                              bottom: null,
                              width: 273.0,
                              height: 18.0,
                              child:
                                  GeneratedDisponhaSequiseroutraartefalecomigoWidget1(),
                            ),
                            Positioned(
                              left: 6.0,
                              top: 430.0,
                              right: null,
                              bottom: null,
                              width: 415.0,
                              height: 98.0,
                              child: GeneratedRectangle61Widget1(),
                            ),
                            Positioned(
                              left: 47.0,
                              top: 445.0,
                              right: null,
                              bottom: null,
                              width: 60.0,
                              height: 60.0,
                              child: GeneratedTest10Widget1(),
                            ),
                            Positioned(
                              left: 118.0,
                              top: 440.0,
                              right: null,
                              bottom: null,
                              width: 131.0,
                              height: 21.0,
                              child: GeneratedAlbertoSanchezWidget1(),
                            ),
                            Positioned(
                              left: 120.0,
                              top: 470.0,
                              right: null,
                              bottom: null,
                              width: 241.0,
                              height: 18.0,
                              child:
                                  GeneratedInfelizmentenoatendonessaregioWidget1(),
                            ),
                            Positioned(
                              left: 317.0,
                              top: 449.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 23.0,
                              child: Generated1600Widget4(),
                            ),
                            Positioned(
                              left: 317.0,
                              top: 542.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 23.0,
                              child: Generated1600Widget5(),
                            ),
                            Positioned(
                              left: 317.0,
                              top: 635.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 23.0,
                              child: Generated1600Widget6(),
                            ),
                            Positioned(
                              left: 317.0,
                              top: 732.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 23.0,
                              child: Generated1600Widget7(),
                            ),
                            Positioned(
                              left: 123.44717407226562,
                              top: 342.0,
                              right: null,
                              bottom: null,
                              width: 95.10565185546875,
                              height: 90.45085144042969,
                              child: GeneratedStar1Widget(),
                            ),
                            Positioned(
                              left: 237.0,
                              top: -17.0,
                              right: null,
                              bottom: null,
                              width: 191.0,
                              height: 943.0,
                              child: GeneratedRectangle50Widget8(),
                            ),
                            Positioned(
                              left: 323.0,
                              top: 129.0,
                              right: null,
                              bottom: null,
                              width: 43.0,
                              height: 29.0,
                              child: GeneratedSairWidget7(),
                            ),
                            Positioned(
                              left: 290.0,
                              top: 36.0,
                              right: null,
                              bottom: null,
                              width: 63.0,
                              height: 29.0,
                              child: GeneratedVoltarWidget7(),
                            ),
                            Positioned(
                              left: 267.0,
                              top: 119.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 45.0,
                              child: GeneratedIconmonstrlogout92401Widget7(),
                            ),
                            Positioned(
                              left: 284.0,
                              top: 39.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 17.22488021850586,
                              child: GeneratedIconmonstrarrow632401Widget7(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
