import 'package:flutter/material.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget1/generated/GeneratedConfirmarSenhaWidget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget1/generated/GeneratedRectangle3Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget1/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget1/generated/GeneratedNomeWidget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget1/generated/GeneratedSenhaWidget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget1/generated/GeneratedCADASTROWidget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget1/generated/GeneratedRectangle4Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget1/generated/GeneratedEllipse1Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget1/generated/GeneratedRectangle13Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget1/generated/GeneratedRectangle13Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget1/generated/GeneratedEmailWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget1/generated/GeneratedSouartistaWidget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget1/generated/GeneratedCadastrarWidget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget1/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget1/generated/GeneratedRectangle5Widget.dart';

/* Frame Tela de Cadastro
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTeladeCadastroWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                          begin: Alignment(0.0, -1.0),
                          end: Alignment(0.0, 0.9999999999999998),
                          stops: [0.0, 0.48767605423927307],
                          colors: [
                            Color.fromARGB(255, 155, 7, 180),
                            Color.fromARGB(255, 69, 8, 95)
                          ],
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            Positioned(
                              left: 52.0,
                              top: 230.0,
                              right: null,
                              bottom: null,
                              width: 320.0,
                              height: 372.0,
                              child: GeneratedRectangle13Widget3(),
                            ),
                            Positioned(
                              left: 90.0,
                              top: 430.0,
                              right: null,
                              bottom: null,
                              width: 250.0,
                              height: 40.0,
                              child: GeneratedRectangle2Widget(),
                            ),
                            Positioned(
                              left: 91.0,
                              top: 507.0,
                              right: null,
                              bottom: null,
                              width: 250.0,
                              height: 40.0,
                              child: GeneratedRectangle4Widget3(),
                            ),
                            Positioned(
                              left: 89.0,
                              top: 285.0,
                              right: null,
                              bottom: null,
                              width: 250.0,
                              height: 40.0,
                              child: GeneratedRectangle3Widget1(),
                            ),
                            Positioned(
                              left: 89.0,
                              top: 362.0,
                              right: null,
                              bottom: null,
                              width: 250.0,
                              height: 40.0,
                              child: GeneratedRectangle5Widget(),
                            ),
                            Positioned(
                              left: 84.0,
                              top: 160.0,
                              right: null,
                              bottom: null,
                              width: 261.0,
                              height: 20.0,
                              child: GeneratedCADASTROWidget1(),
                            ),
                            Positioned(
                              left: 91.0,
                              top: 413.0,
                              right: null,
                              bottom: null,
                              width: 51.0,
                              height: 23.0,
                              child: GeneratedSenhaWidget2(),
                            ),
                            Positioned(
                              left: 91.0,
                              top: 489.0,
                              right: null,
                              bottom: null,
                              width: 125.0,
                              height: 20.0,
                              child: GeneratedConfirmarSenhaWidget1(),
                            ),
                            Positioned(
                              left: 90.0,
                              top: 267.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 23.0,
                              child: GeneratedNomeWidget1(),
                            ),
                            Positioned(
                              left: 91.0,
                              top: 344.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 23.0,
                              child: GeneratedEmailWidget(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 621.0,
                              right: null,
                              bottom: null,
                              width: 49.0,
                              height: 20.0,
                              child: GeneratedRectangle6Widget1(),
                            ),
                            Positioned(
                              left: 123.0,
                              top: 621.0,
                              right: null,
                              bottom: null,
                              width: 92.0,
                              height: 23.0,
                              child: GeneratedSouartistaWidget1(),
                            ),
                            Positioned(
                              left: 73.0,
                              top: 623.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedEllipse1Widget1(),
                            ),
                            Positioned(
                              left: 149.0,
                              top: 687.0,
                              right: null,
                              bottom: null,
                              width: 116.0,
                              height: 40.0,
                              child: GeneratedRectangle13Widget4(),
                            ),
                            Positioned(
                              left: 166.0,
                              top: 696.0,
                              right: null,
                              bottom: null,
                              width: 87.0,
                              height: 26.0,
                              child: GeneratedCadastrarWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
