import 'package:flutter/material.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedErickSebastioWidget16.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedIconmonstrhome624011Widget5.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedRectangle15Widget7.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedRectangle46Widget5.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedTelaInicialWidget15.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedIconmonstrarrow6324013Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedRectangle17Widget6.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedIconmonstrlogout92401Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedRectangle46Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedOlpessoalboatardeMechamoPauloeestouaprocuradeumartistap1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedRectangle49Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedRectangle47Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedVoltarWidget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedFoto_perfil4Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedIconmonstruser1924011Widget5.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedChatdoclienteWidget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/Generated80KWidget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedFoto_perfil1Widget5.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedFoto_perfil5Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedPerfilWidget10.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedSairWidget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedRectangle14Widget6.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedAjudaainamoralquemsabefazeraquarelaChamanochatWidget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedChatWidget15.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedRectangle48Widget5.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedIconmonstrarrow632401Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedEllipse3Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedSamanthaAlvesWidget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedRectangle50Widget5.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedPauloSantiagoWidget15.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedIconmonstrspeechbubble232401Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedIconmonstrthumb22401Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget1/generated/GeneratedIconmonstrspeechbubble724011Widget5.dart';

/* Frame Tela de Home_Artista
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTeladeHome_ArtistaWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 948.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 228, 191, 191),
                              ),
                            ),
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(51, 0, 0, 0),
                              ),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 571.0,
                              right: null,
                              bottom: null,
                              width: 320.0,
                              height: 306.0,
                              child: GeneratedRectangle47Widget1(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 800.0,
                              right: null,
                              bottom: null,
                              width: 96.0,
                              height: 77.0,
                              child: GeneratedRectangle17Widget6(),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 115.0,
                              right: null,
                              bottom: null,
                              width: 361.0,
                              height: 419.0,
                              child: GeneratedRectangle46Widget4(),
                            ),
                            Positioned(
                              left: 74.0,
                              top: 146.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 47.0,
                              child: GeneratedFoto_perfil4Widget1(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 669.0,
                              right: null,
                              bottom: null,
                              width: 299.0,
                              height: 200.0,
                              child: GeneratedRectangle48Widget5(),
                            ),
                            Positioned(
                              left: 143.0,
                              top: 151.0,
                              right: null,
                              bottom: null,
                              width: 111.0,
                              height: 20.0,
                              child: GeneratedPauloSantiagoWidget15(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 600.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 47.0,
                              child: GeneratedFoto_perfil5Widget1(),
                            ),
                            Positioned(
                              left: 143.0,
                              top: 610.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 20.0,
                              child: GeneratedSamanthaAlvesWidget1(),
                            ),
                            Positioned(
                              left: 72.0,
                              top: 247.0,
                              right: null,
                              bottom: null,
                              width: 299.0,
                              height: 200.0,
                              child: GeneratedRectangle49Widget1(),
                            ),
                            Positioned(
                              left: -9.0,
                              top: 850.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 98.0,
                              child: GeneratedRectangle14Widget6(),
                            ),
                            Positioned(
                              left: -2.0,
                              top: 4.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 65.0,
                              child: GeneratedRectangle15Widget7(),
                            ),
                            Positioned(
                              left: 307.0,
                              top: 874.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedIconmonstruser1924011Widget5(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 7.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 47.0,
                              child: GeneratedFoto_perfil1Widget5(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstrhome624011Widget5(),
                            ),
                            Positioned(
                              left: 202.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child:
                                  GeneratedIconmonstrspeechbubble724011Widget5(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 53.0,
                              height: 14.0,
                              child: GeneratedTelaInicialWidget15(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 17.0,
                              child: GeneratedChatWidget15(),
                            ),
                            Positioned(
                              left: 308.0,
                              top: 910.0,
                              right: null,
                              bottom: null,
                              width: 31.0,
                              height: 17.0,
                              child: GeneratedPerfilWidget10(),
                            ),
                            Positioned(
                              left: 71.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 115.0,
                              height: 20.0,
                              child: GeneratedErickSebastioWidget16(),
                            ),
                            Positioned(
                              left: 143.0,
                              top: 171.0,
                              right: null,
                              bottom: null,
                              width: 285.0,
                              height: 38.0,
                              child:
                                  GeneratedOlpessoalboatardeMechamoPauloeestouaprocuradeumartistap1(),
                            ),
                            Positioned(
                              left: 143.0,
                              top: 635.0,
                              right: null,
                              bottom: null,
                              width: 285.0,
                              height: 26.0,
                              child:
                                  GeneratedAjudaainamoralquemsabefazeraquarelaChamanochatWidget1(),
                            ),
                            Positioned(
                              left: 242.0,
                              top: 487.0,
                              right: null,
                              bottom: null,
                              width: 146.0,
                              height: 30.0,
                              child: GeneratedRectangle46Widget5(),
                            ),
                            Positioned(
                              left: 256.0,
                              top: 495.0,
                              right: null,
                              bottom: null,
                              width: 98.0,
                              height: 18.0,
                              child: GeneratedChatdoclienteWidget1(),
                            ),
                            Positioned(
                              left: 133.0,
                              top: 491.0,
                              right: null,
                              bottom: null,
                              width: 31.0,
                              height: 21.0,
                              child: Generated80KWidget1(),
                            ),
                            Positioned(
                              left: 207.0,
                              top: 491.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 22.0,
                              child:
                                  GeneratedIconmonstrspeechbubble232401Widget1(),
                            ),
                            Positioned(
                              left: 82.0,
                              top: 480.0,
                              right: null,
                              bottom: null,
                              width: 36.0,
                              height: 34.0,
                              child: GeneratedEllipse3Widget1(),
                            ),
                            Positioned(
                              left: 89.0,
                              top: 486.0,
                              right: null,
                              bottom: null,
                              width: 21.0,
                              height: 21.0,
                              child: GeneratedIconmonstrthumb22401Widget1(),
                            ),
                            Positioned(
                              left: 341.0,
                              top: 377.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedIconmonstrarrow6324013Widget1(),
                            ),
                            Positioned(
                              left: 237.0,
                              top: -17.0,
                              right: null,
                              bottom: null,
                              width: 191.0,
                              height: 943.0,
                              child: GeneratedRectangle50Widget5(),
                            ),
                            Positioned(
                              left: 292.0,
                              top: 114.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 26.0,
                              child: GeneratedSairWidget4(),
                            ),
                            Positioned(
                              left: 311.0,
                              top: 35.0,
                              right: null,
                              bottom: null,
                              width: 63.0,
                              height: 29.0,
                              child: GeneratedVoltarWidget4(),
                            ),
                            Positioned(
                              left: 254.0,
                              top: 111.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 29.0,
                              child: GeneratedIconmonstrlogout92401Widget4(),
                            ),
                            Positioned(
                              left: 284.0,
                              top: 39.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 17.22488021850586,
                              child: GeneratedIconmonstrarrow632401Widget4(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
