import 'package:flutter/material.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedPin16Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedMapa1Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedTelaInicialWidget9.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedChatWidget9.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedTest1Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedIconmonstruser1924011Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedTest4Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedTest3Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedRectangle15Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedPerfilWidget5.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedIconmonstrspeechbubble724011Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedTela_artistaWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedIconmonstrarrow6324011Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedPin17Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedErickSebastioWidget12.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedPauloSantiagoWidget9.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedFoto_perfil1Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedOlMechamoErickSebastioesouumartistaannimonoramodaspintu8.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedPin13Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedIconmonstrhome624011Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedRectangle17Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedRectangle14Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedRectangle16Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clicar_no_artistawidget/generated/GeneratedTest2Widget1.dart';

/* Frame Tela de Home_Clicar_No_Artista
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTeladeHome_Clicar_No_ArtistaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 948.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                          begin: Alignment(0.0, -1.0),
                          end: Alignment(0.0, 0.9999999999999998),
                          stops: [0.125, 0.921875],
                          colors: [
                            Color.fromARGB(255, 155, 7, 179),
                            Color.fromARGB(255, 69, 8, 95)
                          ],
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(51, 0, 0, 0),
                              ),
                            ),
                            Positioned(
                              left: -262.0,
                              top: 56.0,
                              right: null,
                              bottom: null,
                              width: 1636.0,
                              height: 818.0,
                              child: GeneratedMapa1Widget1(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 585.0,
                              right: null,
                              bottom: null,
                              width: 402.0,
                              height: 348.0,
                              child: GeneratedTela_artistaWidget(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 800.0,
                              right: null,
                              bottom: null,
                              width: 96.0,
                              height: 77.0,
                              child: GeneratedRectangle17Widget1(),
                            ),
                            Positioned(
                              left: 166.0,
                              top: 800.0,
                              right: null,
                              bottom: null,
                              width: 96.0,
                              height: 77.0,
                              child: GeneratedRectangle18Widget(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 800.0,
                              right: null,
                              bottom: null,
                              width: 96.0,
                              height: 77.0,
                              child: GeneratedRectangle20Widget(),
                            ),
                            Positioned(
                              left: 272.0,
                              top: 800.0,
                              right: null,
                              bottom: null,
                              width: 96.0,
                              height: 77.0,
                              child: GeneratedRectangle19Widget(),
                            ),
                            Positioned(
                              left: -9.0,
                              top: 850.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 98.0,
                              child: GeneratedRectangle14Widget2(),
                            ),
                            Positioned(
                              left: -44.0,
                              top: 2.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 65.0,
                              child: GeneratedRectangle15Widget2(),
                            ),
                            Positioned(
                              left: 383.0,
                              top: 20.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedIconmonstrarrow6324011Widget4(),
                            ),
                            Positioned(
                              left: 322.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstruser1924011Widget1(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 7.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 47.0,
                              child: GeneratedFoto_perfil1Widget1(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstrhome624011Widget1(),
                            ),
                            Positioned(
                              left: 202.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child:
                                  GeneratedIconmonstrspeechbubble724011Widget1(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 53.0,
                              height: 14.0,
                              child: GeneratedTelaInicialWidget9(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 17.0,
                              child: GeneratedChatWidget9(),
                            ),
                            Positioned(
                              left: 327.0,
                              top: 902.0,
                              right: null,
                              bottom: null,
                              width: 31.0,
                              height: 17.0,
                              child: GeneratedPerfilWidget5(),
                            ),
                            Positioned(
                              left: 71.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 111.0,
                              height: 20.0,
                              child: GeneratedPauloSantiagoWidget9(),
                            ),
                            Positioned(
                              left: 51.0,
                              top: 440.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 46.0,
                              child: GeneratedPin13Widget(),
                            ),
                            Positioned(
                              left: 59.0,
                              top: 442.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedTest1Widget(),
                            ),
                            Positioned(
                              left: 160.0,
                              top: 472.0,
                              right: null,
                              bottom: null,
                              width: 95.0,
                              height: 95.0,
                              child: GeneratedPin16Widget1(),
                            ),
                            Positioned(
                              left: 176.0,
                              top: 474.0,
                              right: null,
                              bottom: null,
                              width: 63.0,
                              height: 64.0,
                              child: GeneratedTest2Widget1(),
                            ),
                            Positioned(
                              left: 318.0,
                              top: 449.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 46.0,
                              child: GeneratedPin17Widget1(),
                            ),
                            Positioned(
                              left: 326.0,
                              top: 451.0,
                              right: null,
                              bottom: null,
                              width: 31.0,
                              height: 30.0,
                              child: GeneratedTest3Widget1(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 655.0,
                              right: null,
                              bottom: null,
                              width: 95.0,
                              height: 95.0,
                              child: GeneratedTest4Widget1(),
                            ),
                            Positioned(
                              left: 161.0,
                              top: 598.0,
                              right: null,
                              bottom: null,
                              width: 102.0,
                              height: 8.0,
                              child: GeneratedRectangle16Widget1(),
                            ),
                            Positioned(
                              left: 148.0,
                              top: 664.0,
                              right: null,
                              bottom: null,
                              width: 130.0,
                              height: 23.0,
                              child: GeneratedErickSebastioWidget12(),
                            ),
                            Positioned(
                              left: 148.0,
                              top: 695.0,
                              right: null,
                              bottom: null,
                              width: 395.0,
                              height: 85.0,
                              child:
                                  GeneratedOlMechamoErickSebastioesouumartistaannimonoramodaspintu8(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
