import 'package:flutter/material.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladeloginclientewidget1/generated/GeneratedEntrarWidget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladeloginclientewidget1/generated/GeneratedQWidget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladeloginclientewidget1/generated/GeneratedRectangle16Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladeloginclientewidget1/generated/GeneratedPngwing2Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladeloginclientewidget1/generated/GeneratedImageremovebgpreview2Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladeloginclientewidget1/generated/GeneratedSenhaWidget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladeloginclientewidget1/generated/GeneratedArtiWidget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladeloginclientewidget1/generated/GeneratedRectangle17Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladeloginclientewidget1/generated/GeneratedRectangle13Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladeloginclientewidget1/generated/GeneratedLoginWidget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladeloginclientewidget1/generated/GeneratedOxiWidget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladeloginclientewidget1/generated/GeneratedRectangle15Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladeloginclientewidget1/generated/GeneratedLoginWidget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladeloginclientewidget1/generated/GeneratedQWidget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladeloginclientewidget1/generated/GeneratedImageremovebgpreview1Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladeloginclientewidget1/generated/GeneratedRectangle4Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladeloginclientewidget1/generated/GeneratedMarcozeroRecife1280x7201Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladeloginclientewidget1/generated/GeneratedPngwing1Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladeloginclientewidget1/generated/GeneratedMarcozeroRecife1280x7202Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladeloginclientewidget1/generated/GeneratedOxiWidget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladeloginclientewidget1/generated/GeneratedCadastrarseWidget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladeloginclientewidget1/generated/GeneratedArtiWidget2.dart';

/* Frame Tela de Login Cliente
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTeladeLoginClienteWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                          begin: Alignment(0.0, -1.0),
                          end: Alignment(0.0, 0.9999999999999998),
                          stops: [0.125, 0.921875],
                          colors: [
                            Color.fromARGB(255, 155, 7, 179),
                            Color.fromARGB(255, 69, 8, 95)
                          ],
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(51, 0, 0, 0),
                              ),
                            ),
                            Positioned(
                              left: 54.0,
                              top: 526.0,
                              right: null,
                              bottom: null,
                              width: 291.0,
                              height: 166.0,
                              child: GeneratedPngwing1Widget1(),
                            ),
                            Positioned(
                              left: 112.0,
                              top: 557.0,
                              right: null,
                              bottom: null,
                              width: 205.0,
                              height: 35.0,
                              child: GeneratedRectangle4Widget1(),
                            ),
                            Positioned(
                              left: 112.0,
                              top: 539.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 23.0,
                              child: GeneratedLoginWidget2(),
                            ),
                            Positioned(
                              left: 142.0,
                              top: 347.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 170.0,
                              child: GeneratedImageremovebgpreview1Widget1(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 362.0,
                              right: null,
                              bottom: null,
                              width: 114.0,
                              height: 112.0,
                              child: GeneratedMarcozeroRecife1280x7201Widget1(),
                            ),
                            Positioned(
                              left: 90.0,
                              top: 433.0,
                              right: null,
                              bottom: null,
                              width: 246.0,
                              height: 80.0,
                              child: GeneratedQWidget2(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 433.0,
                              right: null,
                              bottom: null,
                              width: 246.0,
                              height: 80.0,
                              child: GeneratedOxiWidget2(),
                            ),
                            Positioned(
                              left: 151.0,
                              top: 433.0,
                              right: null,
                              bottom: null,
                              width: 246.0,
                              height: 80.0,
                              child: GeneratedArtiWidget2(),
                            ),
                            Positioned(
                              left: 52.0,
                              top: 273.0,
                              right: null,
                              bottom: null,
                              width: 320.0,
                              height: 350.0,
                              child: GeneratedRectangle13Widget1(),
                            ),
                            Positioned(
                              left: 54.0,
                              top: 526.0,
                              right: null,
                              bottom: null,
                              width: 291.0,
                              height: 166.0,
                              child: GeneratedPngwing2Widget1(),
                            ),
                            Positioned(
                              left: 86.0,
                              top: 349.0,
                              right: null,
                              bottom: null,
                              width: 250.0,
                              height: 40.0,
                              child: GeneratedRectangle15Widget4(),
                            ),
                            Positioned(
                              left: 86.0,
                              top: 428.0,
                              right: null,
                              bottom: null,
                              width: 250.0,
                              height: 40.0,
                              child: GeneratedRectangle17Widget3(),
                            ),
                            Positioned(
                              left: 86.0,
                              top: 329.0,
                              right: null,
                              bottom: null,
                              width: 51.0,
                              height: 26.0,
                              child: GeneratedLoginWidget3(),
                            ),
                            Positioned(
                              left: 86.0,
                              top: 408.0,
                              right: null,
                              bottom: null,
                              width: 57.0,
                              height: 26.0,
                              child: GeneratedSenhaWidget1(),
                            ),
                            Positioned(
                              left: 160.0,
                              top: 512.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 40.0,
                              child: GeneratedRectangle16Widget3(),
                            ),
                            Positioned(
                              left: 185.0,
                              top: 521.0,
                              right: null,
                              bottom: null,
                              width: 56.0,
                              height: 26.0,
                              child: GeneratedEntrarWidget1(),
                            ),
                            Positioned(
                              left: 131.0,
                              top: 64.0,
                              right: null,
                              bottom: null,
                              width: 133.0,
                              height: 198.0,
                              child: GeneratedImageremovebgpreview2Widget1(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 362.0,
                              right: null,
                              bottom: null,
                              width: 114.0,
                              height: 112.0,
                              child: GeneratedMarcozeroRecife1280x7202Widget1(),
                            ),
                            Positioned(
                              left: 73.0,
                              top: 164.0,
                              right: null,
                              bottom: null,
                              width: 272.0,
                              height: 93.0,
                              child: GeneratedQWidget3(),
                            ),
                            Positioned(
                              left: 11.0,
                              top: 164.0,
                              right: null,
                              bottom: null,
                              width: 272.0,
                              height: 93.0,
                              child: GeneratedOxiWidget3(),
                            ),
                            Positioned(
                              left: 141.0,
                              top: 164.0,
                              right: null,
                              bottom: null,
                              width: 272.0,
                              height: 93.0,
                              child: GeneratedArtiWidget3(),
                            ),
                            Positioned(
                              left: 146.0,
                              top: 699.0,
                              right: null,
                              bottom: null,
                              width: 130.0,
                              height: 26.0,
                              child: GeneratedCadastrarseWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
