import 'package:flutter/material.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedTest3Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedIconmonstrarrow6324012Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedPin17Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedPin18Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedTest4Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedSairWidget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedVoltarWidget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedTelaInicialWidget13.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedTest2Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedRectangle15Widget5.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedPerfilWidget8.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedIconmonstrhome624011Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedPin16Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedChatWidget13.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedRectangle17Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedIconmonstrarrow632401Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedIconmonstrlogout92401Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedIconmonstruser1924011Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedRectangle14Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedPauloSantiagoWidget13.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedIconmonstrspeechbubble724011Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedRectangle50Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedMapa1Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_clientewidget1/generated/GeneratedFoto_perfil1Widget3.dart';

/* Frame Tela de Home_Cliente
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTeladeHome_ClienteWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 948.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                          begin: Alignment(0.0, -1.0),
                          end: Alignment(0.0, 0.9999999999999998),
                          stops: [0.125, 0.921875],
                          colors: [
                            Color.fromARGB(255, 155, 7, 179),
                            Color.fromARGB(255, 69, 8, 95)
                          ],
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(51, 0, 0, 0),
                              ),
                            ),
                            Positioned(
                              left: -398.0,
                              top: 54.0,
                              right: null,
                              bottom: null,
                              width: 1107.2757568359375,
                              height: 818.0,
                              child: GeneratedMapa1Widget3(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 800.0,
                              right: null,
                              bottom: null,
                              width: 96.0,
                              height: 77.0,
                              child: GeneratedRectangle17Widget4(),
                            ),
                            Positioned(
                              left: -9.0,
                              top: 850.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 98.0,
                              child: GeneratedRectangle14Widget4(),
                            ),
                            Positioned(
                              left: -44.0,
                              top: 2.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 65.0,
                              child: GeneratedRectangle15Widget5(),
                            ),
                            Positioned(
                              left: 307.0,
                              top: 874.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedIconmonstruser1924011Widget3(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 7.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 47.0,
                              child: GeneratedFoto_perfil1Widget3(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstrhome624011Widget3(),
                            ),
                            Positioned(
                              left: 202.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child:
                                  GeneratedIconmonstrspeechbubble724011Widget3(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 53.0,
                              height: 14.0,
                              child: GeneratedTelaInicialWidget13(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 17.0,
                              child: GeneratedChatWidget13(),
                            ),
                            Positioned(
                              left: 308.0,
                              top: 910.0,
                              right: null,
                              bottom: null,
                              width: 31.0,
                              height: 17.0,
                              child: GeneratedPerfilWidget8(),
                            ),
                            Positioned(
                              left: 71.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 111.0,
                              height: 20.0,
                              child: GeneratedPauloSantiagoWidget13(),
                            ),
                            Positioned(
                              left: 172.0,
                              top: 587.0,
                              right: null,
                              bottom: null,
                              width: 65.0,
                              height: 65.0,
                              child: GeneratedPin16Widget3(),
                            ),
                            Positioned(
                              left: 183.0,
                              top: 589.0,
                              right: null,
                              bottom: null,
                              width: 43.0,
                              height: 44.0,
                              child: GeneratedTest2Widget3(),
                            ),
                            Positioned(
                              left: 304.0,
                              top: 479.0,
                              right: null,
                              bottom: null,
                              width: 61.0,
                              height: 61.0,
                              child: GeneratedPin17Widget3(),
                            ),
                            Positioned(
                              left: 314.0,
                              top: 481.0,
                              right: null,
                              bottom: null,
                              width: 41.0,
                              height: 41.0,
                              child: GeneratedTest3Widget3(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 472.0,
                              right: null,
                              bottom: null,
                              width: 65.0,
                              height: 65.0,
                              child: GeneratedPin18Widget1(),
                            ),
                            Positioned(
                              left: 74.0,
                              top: 474.0,
                              right: null,
                              bottom: null,
                              width: 43.0,
                              height: 43.0,
                              child: GeneratedTest4Widget3(),
                            ),
                            Positioned(
                              left: 340.0,
                              top: 378.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedIconmonstrarrow6324012Widget2(),
                            ),
                            Positioned(
                              left: 237.0,
                              top: -17.0,
                              right: null,
                              bottom: null,
                              width: 191.0,
                              height: 943.0,
                              child: GeneratedRectangle50Widget4(),
                            ),
                            Positioned(
                              left: 292.0,
                              top: 114.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 26.0,
                              child: GeneratedSairWidget3(),
                            ),
                            Positioned(
                              left: 311.0,
                              top: 35.0,
                              right: null,
                              bottom: null,
                              width: 63.0,
                              height: 29.0,
                              child: GeneratedVoltarWidget3(),
                            ),
                            Positioned(
                              left: 254.0,
                              top: 111.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 29.0,
                              child: GeneratedIconmonstrlogout92401Widget3(),
                            ),
                            Positioned(
                              left: 284.0,
                              top: 39.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 17.22488021850586,
                              child: GeneratedIconmonstrarrow632401Widget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
