import 'package:flutter/material.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedErickSebastioWidget15.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedPerfilWidget9.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedIconmonstruser1924011Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedSamanthaAlvesWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedRectangle17Widget5.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedRectangle46Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedFoto_perfil5Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedRectangle46Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/Generated80KWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedChatWidget14.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedIconmonstrarrow6324013Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedPauloSantiagoWidget14.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedRectangle47Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedTelaInicialWidget14.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedChatdoclienteWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedIconmonstrthumb22401Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedIconmonstrhome624011Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedAjudaainamoralquemsabefazeraquarelaChamanochatWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedRectangle14Widget5.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedOlpessoalboatardeMechamoPauloeestouaprocuradeumartistap.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedIconmonstrspeechbubble232401Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedFoto_perfil4Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedRectangle15Widget6.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedRectangle48Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedIconmonstrspeechbubble724011Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedFoto_perfil1Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladehome_artistawidget/generated/GeneratedRectangle49Widget.dart';

/* Frame Tela de Home_Artista
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTeladeHome_ArtistaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 948.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 228, 191, 191),
                              ),
                            ),
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(51, 0, 0, 0),
                              ),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 571.0,
                              right: null,
                              bottom: null,
                              width: 361.0,
                              height: 306.0,
                              child: GeneratedRectangle47Widget(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 800.0,
                              right: null,
                              bottom: null,
                              width: 96.0,
                              height: 77.0,
                              child: GeneratedRectangle17Widget5(),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 115.0,
                              right: null,
                              bottom: null,
                              width: 361.0,
                              height: 419.0,
                              child: GeneratedRectangle46Widget2(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 146.0,
                              right: null,
                              bottom: null,
                              width: 56.16999816894531,
                              height: 54.99979019165039,
                              child: GeneratedFoto_perfil4Widget(),
                            ),
                            Positioned(
                              left: 133.0,
                              top: 151.0,
                              right: null,
                              bottom: null,
                              width: 147.0,
                              height: 26.0,
                              child: GeneratedPauloSantiagoWidget14(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 614.0,
                              right: null,
                              bottom: null,
                              width: 56.17021560668945,
                              height: 55.0,
                              child: GeneratedFoto_perfil5Widget(),
                            ),
                            Positioned(
                              left: 133.0,
                              top: 615.0,
                              right: null,
                              bottom: null,
                              width: 159.0,
                              height: 26.0,
                              child: GeneratedSamanthaAlvesWidget(),
                            ),
                            Positioned(
                              left: 72.0,
                              top: 691.0,
                              right: null,
                              bottom: null,
                              width: 299.0,
                              height: 200.0,
                              child: GeneratedRectangle49Widget(),
                            ),
                            Positioned(
                              left: -9.0,
                              top: 850.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 98.0,
                              child: GeneratedRectangle14Widget5(),
                            ),
                            Positioned(
                              left: -59.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 65.0,
                              child: GeneratedRectangle15Widget6(),
                            ),
                            Positioned(
                              left: 322.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstruser1924011Widget4(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 7.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 47.0,
                              child: GeneratedFoto_perfil1Widget4(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstrhome624011Widget4(),
                            ),
                            Positioned(
                              left: 202.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child:
                                  GeneratedIconmonstrspeechbubble724011Widget4(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 53.0,
                              height: 14.0,
                              child: GeneratedTelaInicialWidget14(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 17.0,
                              child: GeneratedChatWidget14(),
                            ),
                            Positioned(
                              left: 327.0,
                              top: 902.0,
                              right: null,
                              bottom: null,
                              width: 31.0,
                              height: 17.0,
                              child: GeneratedPerfilWidget9(),
                            ),
                            Positioned(
                              left: 71.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 115.0,
                              height: 20.0,
                              child: GeneratedErickSebastioWidget15(),
                            ),
                            Positioned(
                              left: 72.0,
                              top: 247.0,
                              right: null,
                              bottom: null,
                              width: 299.0,
                              height: 200.0,
                              child: GeneratedRectangle48Widget4(),
                            ),
                            Positioned(
                              left: 133.0,
                              top: 178.0,
                              right: null,
                              bottom: null,
                              width: 285.0,
                              height: 41.0,
                              child:
                                  GeneratedOlpessoalboatardeMechamoPauloeestouaprocuradeumartistap(),
                            ),
                            Positioned(
                              left: 133.0,
                              top: 643.0,
                              right: null,
                              bottom: null,
                              width: 285.0,
                              height: 28.0,
                              child:
                                  GeneratedAjudaainamoralquemsabefazeraquarelaChamanochatWidget(),
                            ),
                            Positioned(
                              left: 240.0,
                              top: 479.0,
                              right: null,
                              bottom: null,
                              width: 150.0,
                              height: 40.0,
                              child: GeneratedRectangle46Widget3(),
                            ),
                            Positioned(
                              left: 261.0,
                              top: 491.0,
                              right: null,
                              bottom: null,
                              width: 112.0,
                              height: 20.0,
                              child: GeneratedChatdoclienteWidget(),
                            ),
                            Positioned(
                              left: 133.0,
                              top: 491.0,
                              right: null,
                              bottom: null,
                              width: 31.0,
                              height: 21.0,
                              child: Generated80KWidget(),
                            ),
                            Positioned(
                              left: 207.0,
                              top: 491.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 22.0,
                              child:
                                  GeneratedIconmonstrspeechbubble232401Widget(),
                            ),
                            Positioned(
                              left: 82.0,
                              top: 480.0,
                              right: null,
                              bottom: null,
                              width: 36.0,
                              height: 34.0,
                              child: GeneratedEllipse3Widget(),
                            ),
                            Positioned(
                              left: 89.0,
                              top: 486.0,
                              right: null,
                              bottom: null,
                              width: 21.0,
                              height: 21.0,
                              child: GeneratedIconmonstrthumb22401Widget(),
                            ),
                            Positioned(
                              left: 382.0,
                              top: 20.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedIconmonstrarrow6324013Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
