import 'package:flutter/material.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget1/generated/GeneratedFechadoAmanhestareiaiparaoserviWidget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget1/generated/GeneratedPauloSantiagoWidget22.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget1/generated/GeneratedVoltarWidget8.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget1/generated/Generated1600Widget9.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget1/generated/GeneratedTest11Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget1/generated/GeneratedIconmonstrspeechbubble724015Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget1/generated/GeneratedRectangle50Widget9.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget1/generated/GeneratedIconmonstrarrow632401Widget8.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget1/generated/GeneratedRectangle58Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget1/generated/GeneratedErickSebastioWidget24.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget1/generated/GeneratedChatWidget24.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget1/generated/GeneratedFoto_perfil6Widget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget1/generated/GeneratedIconmonstrhome624015Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget1/generated/GeneratedRectangle57Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget1/generated/GeneratedPerfilWidget17.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget1/generated/GeneratedIconmonstrarrow6324013Widget6.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget1/generated/GeneratedIconmonstrlogout92401Widget8.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget1/generated/GeneratedIconmonstruser1924014Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget1/generated/GeneratedTelaInicialWidget24.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget1/generated/GeneratedRectangle18Widget5.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_artista_chatswidget1/generated/GeneratedSairWidget8.dart';

/* Frame Tela_Artista_Chats
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTela_Artista_ChatsWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 948.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 249, 234, 234),
                              ),
                            ),
                            Positioned(
                              left: -41.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 65.0,
                              child: GeneratedRectangle18Widget5(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 7.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 47.0,
                              child: GeneratedFoto_perfil6Widget1(),
                            ),
                            Positioned(
                              left: 71.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 115.0,
                              height: 20.0,
                              child: GeneratedErickSebastioWidget24(),
                            ),
                            Positioned(
                              left: 6.0,
                              top: 89.0,
                              right: null,
                              bottom: null,
                              width: 415.0,
                              height: 98.0,
                              child: GeneratedRectangle58Widget3(),
                            ),
                            Positioned(
                              left: 383.0,
                              top: 20.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedIconmonstrarrow6324013Widget6(),
                            ),
                            Positioned(
                              left: -9.0,
                              top: 850.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 98.0,
                              child: GeneratedRectangle57Widget3(),
                            ),
                            Positioned(
                              left: 322.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstruser1924014Widget3(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 53.0,
                              height: 14.0,
                              child: GeneratedTelaInicialWidget24(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 17.0,
                              child: GeneratedChatWidget24(),
                            ),
                            Positioned(
                              left: 202.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child:
                                  GeneratedIconmonstrspeechbubble724015Widget3(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstrhome624015Widget3(),
                            ),
                            Positioned(
                              left: 327.0,
                              top: 902.0,
                              right: null,
                              bottom: null,
                              width: 31.0,
                              height: 17.0,
                              child: GeneratedPerfilWidget17(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 104.0,
                              right: null,
                              bottom: null,
                              width: 62.0,
                              height: 62.0,
                              child: GeneratedTest11Widget1(),
                            ),
                            Positioned(
                              left: 117.0,
                              top: 105.0,
                              right: null,
                              bottom: null,
                              width: 118.0,
                              height: 21.0,
                              child: GeneratedPauloSantiagoWidget22(),
                            ),
                            Positioned(
                              left: 119.0,
                              top: 127.0,
                              right: null,
                              bottom: null,
                              width: 224.0,
                              height: 15.0,
                              child:
                                  GeneratedFechadoAmanhestareiaiparaoserviWidget1(),
                            ),
                            Positioned(
                              left: 345.0,
                              top: 105.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 23.0,
                              child: Generated1600Widget9(),
                            ),
                            Positioned(
                              left: 237.0,
                              top: -17.0,
                              right: null,
                              bottom: null,
                              width: 191.0,
                              height: 943.0,
                              child: GeneratedRectangle50Widget9(),
                            ),
                            Positioned(
                              left: 291.0,
                              top: 114.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 26.0,
                              child: GeneratedSairWidget8(),
                            ),
                            Positioned(
                              left: 311.0,
                              top: 35.0,
                              right: null,
                              bottom: null,
                              width: 63.0,
                              height: 29.0,
                              child: GeneratedVoltarWidget8(),
                            ),
                            Positioned(
                              left: 254.0,
                              top: 111.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 29.0,
                              child: GeneratedIconmonstrlogout92401Widget8(),
                            ),
                            Positioned(
                              left: 284.0,
                              top: 39.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 17.22488021850586,
                              child: GeneratedIconmonstrarrow632401Widget8(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
