import 'package:flutter/material.dart';
import 'package:flutterapp/oxiqartiapp/generatedabalateral_clientewidget/generated/GeneratedSairWidget6.dart';
import 'package:flutterapp/oxiqartiapp/generatedabalateral_clientewidget/generated/GeneratedIconmonstruser1924013Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedabalateral_clientewidget/generated/GeneratedTelaInicialWidget20.dart';
import 'package:flutterapp/oxiqartiapp/generatedabalateral_clientewidget/generated/GeneratedRectangle50Widget7.dart';
import 'package:flutterapp/oxiqartiapp/generatedabalateral_clientewidget/generated/GeneratedTest8Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedabalateral_clientewidget/generated/GeneratedIconmonstrspeechbubble724014Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedabalateral_clientewidget/generated/GeneratedPerfilWidget13.dart';
import 'package:flutterapp/oxiqartiapp/generatedabalateral_clientewidget/generated/GeneratedIconmonstrlogout92401Widget6.dart';
import 'package:flutterapp/oxiqartiapp/generatedabalateral_clientewidget/generated/GeneratedRectangle53Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedabalateral_clientewidget/generated/GeneratedIconmonstrarrow6324013Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedabalateral_clientewidget/generated/GeneratedIconmonstrlinethreeverticallined2402Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedabalateral_clientewidget/generated/GeneratedRectangle52Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedabalateral_clientewidget/generated/GeneratedOlMechamopauloecomproserviosartisticosWidget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedabalateral_clientewidget/generated/GeneratedIconmonstrarrow632401Widget6.dart';
import 'package:flutterapp/oxiqartiapp/generatedabalateral_clientewidget/generated/GeneratedChatWidget20.dart';
import 'package:flutterapp/oxiqartiapp/generatedabalateral_clientewidget/generated/GeneratedVoltarWidget6.dart';
import 'package:flutterapp/oxiqartiapp/generatedabalateral_clientewidget/generated/GeneratedIconmonstrhome624014Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedabalateral_clientewidget/generated/GeneratedRectangle51Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedabalateral_clientewidget/generated/GeneratedPauloSantiagoWidget18.dart';

/* Frame Aba lateral_Cliente
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAbalateral_ClienteWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 948.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(181, 228, 191, 191),
                              ),
                            ),
                            Positioned(
                              left: 156.0,
                              top: 152.0,
                              right: null,
                              bottom: null,
                              width: 213.0,
                              height: 85.0,
                              child:
                                  GeneratedOlMechamopauloecomproserviosartisticosWidget1(),
                            ),
                            Positioned(
                              left: 156.0,
                              top: 122.0,
                              right: null,
                              bottom: null,
                              width: 147.0,
                              height: 26.0,
                              child: GeneratedPauloSantiagoWidget18(),
                            ),
                            Positioned(
                              left: 364.7998352050781,
                              top: 404.9759826660156,
                              right: null,
                              bottom: null,
                              width: 36.0,
                              height: 36.0,
                              child:
                                  GeneratedIconmonstrlinethreeverticallined2402Widget(),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 291.0,
                              right: null,
                              bottom: null,
                              width: 119.0,
                              height: 119.0,
                              child: GeneratedRectangle51Widget(),
                            ),
                            Positioned(
                              left: -9.0,
                              top: 850.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 98.0,
                              child: GeneratedRectangle52Widget(),
                            ),
                            Positioned(
                              left: 307.5,
                              top: 874.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedIconmonstruser1924013Widget(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstrhome624014Widget(),
                            ),
                            Positioned(
                              left: 202.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child:
                                  GeneratedIconmonstrspeechbubble724014Widget(),
                            ),
                            Positioned(
                              left: 341.5,
                              top: 383.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedIconmonstrarrow6324013Widget2(),
                            ),
                            Positioned(
                              left: 237.0,
                              top: -17.0,
                              right: null,
                              bottom: null,
                              width: 191.0,
                              height: 943.0,
                              child: GeneratedRectangle50Widget7(),
                            ),
                            Positioned(
                              left: 333.0,
                              top: 129.0,
                              right: null,
                              bottom: null,
                              width: 43.0,
                              height: 29.0,
                              child: GeneratedSairWidget6(),
                            ),
                            Positioned(
                              left: 297.0,
                              top: 36.0,
                              right: null,
                              bottom: null,
                              width: 63.0,
                              height: 29.0,
                              child: GeneratedVoltarWidget6(),
                            ),
                            Positioned(
                              left: 267.0,
                              top: 119.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 45.0,
                              child: GeneratedIconmonstrlogout92401Widget6(),
                            ),
                            Positioned(
                              left: 284.0,
                              top: 39.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 17.22488021850586,
                              child: GeneratedIconmonstrarrow632401Widget6(),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 104.0,
                              right: null,
                              bottom: null,
                              width: 120.0,
                              height: 120.0,
                              child: GeneratedTest8Widget(),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 291.0,
                              right: null,
                              bottom: null,
                              width: 119.0,
                              height: 119.0,
                              child: GeneratedRectangle53Widget(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 53.0,
                              height: 14.0,
                              child: GeneratedTelaInicialWidget20(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 17.0,
                              child: GeneratedChatWidget20(),
                            ),
                            Positioned(
                              left: 309.5,
                              top: 910.0,
                              right: null,
                              bottom: null,
                              width: 31.0,
                              height: 17.0,
                              child: GeneratedPerfilWidget13(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
