import 'package:flutter/material.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedIconmonstrhome624012Widget7.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedIconmonstrspeechbubble724012Widget7.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedRectangle48Widget6.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedRectangle47Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedIconmonstrarrow6324011Widget6.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedTelaInicialWidget29.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedExcelenteWidget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedAvalieoartistaWidget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedIcons8estrela641Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedRectangle32Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedRectangle28Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedRectangle27Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedRectangle25Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedRectangle21Widget12.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedeehWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedEnviarWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedBemvindoaavaliaodoArtistaWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedIconmonstruser1924012Widget7.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedIconmonstrspeechbubble62401Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedErickSebastioWidget27.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedChatWidget29.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedPerfilWidget22.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedRectangle30Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedRectangle29Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedRectangle14Widget9.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedRuimWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedOlMechamoErickSebastioesouumartistaannimonoramodaspintu15.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedBomWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedRectangle23Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedMedianoWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedTest5Widget6.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedFoto_perfil2Widget8.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedImageremovebgpreview3Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedPauloSantiagoWidget25.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedCancelarWidget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedRectangle31Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedRectangle26Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedAvalieoartistaWidget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedRectangle46Widget6.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_avaliaowidget/generated/GeneratedFalarcomartistaWidget11.dart';

/* Frame Tela_Avaliação
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTela_AvaliaoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 948.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 105.0,
                              right: null,
                              bottom: null,
                              width: 95.0,
                              height: 95.0,
                              child: GeneratedTest5Widget6(),
                            ),
                            Positioned(
                              left: 141.0,
                              top: 105.0,
                              right: null,
                              bottom: null,
                              width: 122.0,
                              height: 21.0,
                              child: GeneratedErickSebastioWidget27(),
                            ),
                            Positioned(
                              left: 141.0,
                              top: 138.0,
                              right: null,
                              bottom: null,
                              width: 213.0,
                              height: 85.0,
                              child:
                                  GeneratedOlMechamoErickSebastioesouumartistaannimonoramodaspintu15(),
                            ),
                            Positioned(
                              left: -44.0,
                              top: 2.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 65.0,
                              child: GeneratedRectangle47Widget2(),
                            ),
                            Positioned(
                              left: 350.0,
                              top: 381.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedIconmonstrarrow6324011Widget6(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 7.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 47.0,
                              child: GeneratedFoto_perfil2Widget8(),
                            ),
                            Positioned(
                              left: 75.0,
                              top: 18.0,
                              right: null,
                              bottom: null,
                              width: 118.0,
                              height: 21.0,
                              child: GeneratedPauloSantiagoWidget25(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 360.0,
                              right: null,
                              bottom: null,
                              width: 119.0,
                              height: 120.0,
                              child: GeneratedRectangle25Widget2(),
                            ),
                            Positioned(
                              left: 297.0,
                              top: 363.0,
                              right: null,
                              bottom: null,
                              width: 119.0,
                              height: 120.0,
                              child: GeneratedRectangle48Widget6(),
                            ),
                            Positioned(
                              left: 163.0,
                              top: 360.0,
                              right: null,
                              bottom: null,
                              width: 119.0,
                              height: 120.0,
                              child: GeneratedRectangle23Widget2(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 498.0,
                              right: null,
                              bottom: null,
                              width: 119.0,
                              height: 120.0,
                              child: GeneratedRectangle26Widget2(),
                            ),
                            Positioned(
                              left: 163.0,
                              top: 498.0,
                              right: null,
                              bottom: null,
                              width: 119.0,
                              height: 120.0,
                              child: GeneratedRectangle27Widget2(),
                            ),
                            Positioned(
                              left: 298.0,
                              top: 498.0,
                              right: null,
                              bottom: null,
                              width: 119.0,
                              height: 120.0,
                              child: GeneratedRectangle28Widget2(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 637.0,
                              right: null,
                              bottom: null,
                              width: 119.0,
                              height: 119.0,
                              child: GeneratedRectangle29Widget2(),
                            ),
                            Positioned(
                              left: 163.0,
                              top: 637.0,
                              right: null,
                              bottom: null,
                              width: 119.0,
                              height: 119.0,
                              child: GeneratedRectangle30Widget2(),
                            ),
                            Positioned(
                              left: 298.0,
                              top: 637.0,
                              right: null,
                              bottom: null,
                              width: 119.0,
                              height: 119.0,
                              child: GeneratedRectangle31Widget2(),
                            ),
                            Positioned(
                              left: -9.0,
                              top: 850.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 98.0,
                              child: GeneratedRectangle21Widget12(),
                            ),
                            Positioned(
                              left: 322.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstruser1924012Widget7(),
                            ),
                            Positioned(
                              left: 202.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child:
                                  GeneratedIconmonstrspeechbubble724012Widget7(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 53.0,
                              height: 14.0,
                              child: GeneratedTelaInicialWidget29(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 17.0,
                              child: GeneratedChatWidget29(),
                            ),
                            Positioned(
                              left: 327.0,
                              top: 902.0,
                              right: null,
                              bottom: null,
                              width: 31.0,
                              height: 17.0,
                              child: GeneratedPerfilWidget22(),
                            ),
                            Positioned(
                              left: 263.0,
                              top: 790.0,
                              right: null,
                              bottom: null,
                              width: 153.0,
                              height: 38.0,
                              child: GeneratedRectangle32Widget3(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 270.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 40.0,
                              child: GeneratedRectangle46Widget6(),
                            ),
                            Positioned(
                              left: 67.0,
                              top: 282.0,
                              right: null,
                              bottom: null,
                              width: 95.0,
                              height: 18.0,
                              child: GeneratedAvalieoartistaWidget2(),
                            ),
                            Positioned(
                              left: 299.0,
                              top: 800.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 18.0,
                              child: GeneratedFalarcomartistaWidget11(),
                            ),
                            Positioned(
                              left: 272.0,
                              top: 796.0,
                              right: null,
                              bottom: null,
                              width: 25.0,
                              height: 25.0,
                              child:
                                  GeneratedIconmonstrspeechbubble62401Widget2(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstrhome624012Widget7(),
                            ),
                            Positioned(
                              left: 95.0,
                              top: 534.0,
                              right: null,
                              bottom: null,
                              width: 88.0,
                              height: 17.0,
                              child: GeneratedAvalieoartistaWidget3(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 277.0,
                              right: null,
                              bottom: null,
                              width: 26.0,
                              height: 26.0,
                              child: GeneratedIcons8estrela641Widget2(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 331.0,
                              right: null,
                              bottom: null,
                              width: 320.0,
                              height: 263.0,
                              child: GeneratedRectangle14Widget9(),
                            ),
                            Positioned(
                              left: 102.0,
                              top: 359.0,
                              right: null,
                              bottom: null,
                              width: 246.0,
                              height: 20.0,
                              child: GeneratedBemvindoaavaliaodoArtistaWidget(),
                            ),
                            Positioned(
                              left: 88.0,
                              top: 397.0,
                              right: null,
                              bottom: null,
                              width: 270.0,
                              height: 59.26829147338867,
                              child: GeneratedImageremovebgpreview3Widget(),
                            ),
                            Positioned(
                              left: 228.0,
                              top: 519.0,
                              right: null,
                              bottom: null,
                              width: 130.0,
                              height: 40.0,
                              child: GeneratedRectangle22Widget(),
                            ),
                            Positioned(
                              left: 264.0,
                              top: 527.0,
                              right: null,
                              bottom: null,
                              width: 66.0,
                              height: 29.0,
                              child: GeneratedEnviarWidget(),
                            ),
                            Positioned(
                              left: 126.0,
                              top: 529.0,
                              right: null,
                              bottom: null,
                              width: 79.0,
                              height: 26.0,
                              child: GeneratedCancelarWidget1(),
                            ),
                            Positioned(
                              left: 100.0,
                              top: 451.0,
                              right: null,
                              bottom: null,
                              width: 25.0,
                              height: 15.0,
                              child: GeneratedRuimWidget(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 451.0,
                              right: null,
                              bottom: null,
                              width: 25.0,
                              height: 15.0,
                              child: GeneratedeehWidget(),
                            ),
                            Positioned(
                              left: 207.0,
                              top: 451.0,
                              right: null,
                              bottom: null,
                              width: 39.0,
                              height: 15.0,
                              child: GeneratedMedianoWidget(),
                            ),
                            Positioned(
                              left: 272.0,
                              top: 451.0,
                              right: null,
                              bottom: null,
                              width: 23.0,
                              height: 15.0,
                              child: GeneratedBomWidget(),
                            ),
                            Positioned(
                              left: 319.0,
                              top: 451.0,
                              right: null,
                              bottom: null,
                              width: 43.0,
                              height: 15.0,
                              child: GeneratedExcelenteWidget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
