import 'package:flutter/material.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget/generated/GeneratedRectangle4Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget/generated/GeneratedMarcaressaoporesultaremmudanasemalgumasferramentasnoseu.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget/generated/GeneratedCADASTROWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget/generated/GeneratedContinuarWidget1.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget/generated/GeneratedCancelarWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget/generated/GeneratedSouartistaWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget/generated/GeneratedRectangle13Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget/generated/GeneratedRectangle14Widget8.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget/generated/GeneratedConfirmarSenhaWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget/generated/GeneratedRectangle14Widget7.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget/generated/GeneratedNomeWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget/generated/GeneratedCadastrarWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget/generated/GeneratedContinuarWidget.dart';
import 'package:flutterapp/oxiqartiapp/generatedteladecadastrowidget/generated/GeneratedRectangle21Widget9.dart';

/* Frame Tela de Cadastro
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTeladeCadastroWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                          begin: Alignment(0.0, -1.0),
                          end: Alignment(0.0, 0.9999999999999998),
                          stops: [0.0, 0.48767605423927307],
                          colors: [
                            Color.fromARGB(255, 155, 7, 180),
                            Color.fromARGB(255, 69, 8, 95)
                          ],
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            Positioned(
                              left: 52.0,
                              top: 230.0,
                              right: null,
                              bottom: null,
                              width: 320.0,
                              height: 372.0,
                              child: GeneratedRectangle14Widget7(),
                            ),
                            Positioned(
                              left: 91.0,
                              top: 507.0,
                              right: null,
                              bottom: null,
                              width: 250.0,
                              height: 40.0,
                              child: GeneratedRectangle4Widget2(),
                            ),
                            Positioned(
                              left: 89.0,
                              top: 285.0,
                              right: null,
                              bottom: null,
                              width: 250.0,
                              height: 40.0,
                              child: GeneratedRectangle3Widget(),
                            ),
                            Positioned(
                              left: 84.0,
                              top: 160.0,
                              right: null,
                              bottom: null,
                              width: 261.0,
                              height: 20.0,
                              child: GeneratedCADASTROWidget(),
                            ),
                            Positioned(
                              left: 91.0,
                              top: 489.0,
                              right: null,
                              bottom: null,
                              width: 125.0,
                              height: 20.0,
                              child: GeneratedConfirmarSenhaWidget(),
                            ),
                            Positioned(
                              left: 90.0,
                              top: 267.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 23.0,
                              child: GeneratedNomeWidget(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 621.0,
                              right: null,
                              bottom: null,
                              width: 49.0,
                              height: 20.0,
                              child: GeneratedRectangle6Widget(),
                            ),
                            Positioned(
                              left: 123.0,
                              top: 621.0,
                              right: null,
                              bottom: null,
                              width: 92.0,
                              height: 23.0,
                              child: GeneratedSouartistaWidget(),
                            ),
                            Positioned(
                              left: 73.0,
                              top: 623.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedEllipse1Widget(),
                            ),
                            Positioned(
                              left: 149.0,
                              top: 687.0,
                              right: null,
                              bottom: null,
                              width: 116.0,
                              height: 40.0,
                              child: GeneratedRectangle13Widget2(),
                            ),
                            Positioned(
                              left: 166.0,
                              top: 696.0,
                              right: null,
                              bottom: null,
                              width: 87.0,
                              height: 26.0,
                              child: GeneratedCadastrarWidget(),
                            ),
                            Positioned(
                              left: 87.0,
                              top: 330.0,
                              right: null,
                              bottom: null,
                              width: 255.0,
                              height: 180.0,
                              child: GeneratedRectangle14Widget8(),
                            ),
                            Positioned(
                              left: 106.0,
                              top: 345.0,
                              right: null,
                              bottom: null,
                              width: 217.0,
                              height: 56.0,
                              child:
                                  GeneratedMarcaressaoporesultaremmudanasemalgumasferramentasnoseu(),
                            ),
                            Positioned(
                              left: 171.0,
                              top: 410.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 24.0,
                              child: GeneratedContinuarWidget(),
                            ),
                            Positioned(
                              left: 221.0,
                              top: 445.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 35.0,
                              child: GeneratedRectangle21Widget9(),
                            ),
                            Positioned(
                              left: 236.0,
                              top: 454.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 23.0,
                              child: GeneratedContinuarWidget1(),
                            ),
                            Positioned(
                              left: 122.0,
                              top: 454.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 23.0,
                              child: GeneratedCancelarWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
