import 'package:flutter/material.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget3/generated/GeneratedEllipse5Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget3/generated/GeneratedRectangle50Widget13.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget3/generated/GeneratedPerfilWidget21.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget3/generated/GeneratedFrame27Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget3/generated/GeneratedErickSebastioWidget26.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget3/generated/GeneratedRectangle1Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget3/generated/GeneratedRectangle51Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget3/generated/GeneratedTelaInicialWidget28.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget3/generated/GeneratedVoltarWidget10.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget3/generated/GeneratedLine26Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget3/generated/GeneratedChatWidget28.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget3/generated/GeneratedSairWidget10.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget3/generated/GeneratedIconmonstrarrow6324014Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget3/generated/GeneratedIconmonstrarrow6324015Widget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget3/generated/GeneratedDigiteumtextoWidget3.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget3/generated/GeneratedRectangle52Widget2.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget3/generated/GeneratedIconmonstrhome624014Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget3/generated/GeneratedIconmonstrlogout92401Widget10.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget3/generated/GeneratedIconmonstrarrow632401Widget10.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget3/generated/GeneratedIconmonstruser1924013Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget3/generated/GeneratedIconmonstrspeechbubble724014Widget4.dart';
import 'package:flutterapp/oxiqartiapp/generatedtela_chat_clientewidget3/generated/GeneratedFoto_perfil6Widget3.dart';

/* Frame Tela_Chat_Cliente
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTela_Chat_ClienteWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 948.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: -44.0,
                              top: 2.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 65.0,
                              child: GeneratedRectangle50Widget13(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 7.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 47.0,
                              child: GeneratedFoto_perfil6Widget3(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 19.0,
                              right: null,
                              bottom: null,
                              width: 152.0,
                              height: 26.0,
                              child: GeneratedErickSebastioWidget26(),
                            ),
                            Positioned(
                              left: 383.0,
                              top: 20.0,
                              right: null,
                              bottom: null,
                              width: 20.0,
                              height: 20.0,
                              child: GeneratedIconmonstrarrow6324014Widget3(),
                            ),
                            Positioned(
                              left: 338.0,
                              top: 801.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 15.0,
                              child: GeneratedIconmonstrarrow6324015Widget3(),
                            ),
                            Positioned(
                              left: -3.0,
                              top: 850.0,
                              right: null,
                              bottom: null,
                              width: 524.0,
                              height: 98.0,
                              child: GeneratedRectangle51Widget4(),
                            ),
                            Positioned(
                              left: 322.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstruser1924013Widget4(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child: GeneratedIconmonstrhome624014Widget4(),
                            ),
                            Positioned(
                              left: 202.0,
                              top: 858.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 37.0,
                              child:
                                  GeneratedIconmonstrspeechbubble724014Widget4(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 53.0,
                              height: 14.0,
                              child: GeneratedTelaInicialWidget28(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 904.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 17.0,
                              child: GeneratedChatWidget28(),
                            ),
                            Positioned(
                              left: 327.0,
                              top: 902.0,
                              right: null,
                              bottom: null,
                              width: 31.0,
                              height: 17.0,
                              child: GeneratedPerfilWidget21(),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 779.0,
                              right: null,
                              bottom: null,
                              width: 338.0,
                              height: 56.0,
                              child: GeneratedRectangle1Widget3(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 798.0,
                              right: null,
                              bottom: null,
                              width: 203.0,
                              height: 17.0,
                              child: GeneratedDigiteumtextoWidget3(),
                            ),
                            Positioned(
                              left: 317.0,
                              top: 793.0,
                              right: null,
                              bottom: null,
                              width: 29.0,
                              height: 1.0,
                              child: GeneratedLine26Widget3(),
                            ),
                            Positioned(
                              left: 328.0,
                              top: 791.0,
                              right: null,
                              bottom: null,
                              width: 35.0,
                              height: 35.0,
                              child: GeneratedEllipse5Widget3(),
                            ),
                            Positioned(
                              left: 51.0,
                              top: 90.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 625.0,
                              child: GeneratedFrame27Widget3(),
                            ),
                            Positioned(
                              left: 237.0,
                              top: -17.0,
                              right: null,
                              bottom: null,
                              width: 191.0,
                              height: 943.0,
                              child: GeneratedRectangle52Widget2(),
                            ),
                            Positioned(
                              left: 267.0,
                              top: 119.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 45.0,
                              child: GeneratedIconmonstrlogout92401Widget10(),
                            ),
                            Positioned(
                              left: 323.0,
                              top: 129.0,
                              right: null,
                              bottom: null,
                              width: 43.0,
                              height: 29.0,
                              child: GeneratedSairWidget10(),
                            ),
                            Positioned(
                              left: 284.0,
                              top: 39.0,
                              right: null,
                              bottom: null,
                              width: 15.0,
                              height: 17.22488021850586,
                              child: GeneratedIconmonstrarrow632401Widget10(),
                            ),
                            Positioned(
                              left: 290.0,
                              top: 36.0,
                              right: null,
                              bottom: null,
                              width: 63.0,
                              height: 29.0,
                              child: GeneratedVoltarWidget10(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
